#!/usr/bin/ruby

File.new("htmlAscii.js", "w")
File.open("htmlAscii.js", "w") do |f|
    f.write("var htmlAscii = [")
    for i in 32..126
        f.write("'&#" + i.to_s() + ";', ")
    end
    
    for i in 160..255
        f.write("'&#" + i.to_s() + ";', ")
    end
    
    for i in 338..402
        f.write("'&#" + i.to_s() + ";', ")
    end
    
    for i in 8211..8482
        f.write("'&#" + i.to_s() + ";', ")
    end
    
    f.write("'&quot;', ")
    f.write("'&amp;', ")
    f.write("'&lt;', ")
    f.write("'&gt;', ")
    f.write("'&nbsp;', ")
    f.write("'&iexcl;', ")
    f.write("'&cent;', ")
    f.write("'&pound;', ")
    f.write("'&curren;', ")
    f.write("'&yen;', ")
    f.write("'&brvbar;', ")
    f.write("'&sect;', ")
    f.write("'&uml;', ")
    f.write("'&copy;', ")
    f.write("'&ordf;', ")
    f.write("'&laquo;', ")
    f.write("'&not;', ")
    f.write("'&shy;', ")
    f.write("'&reg;', ")
    f.write("'&macr;', ")
    f.write("'&deg;', ")
    f.write("'&plusmn;', ")
    f.write("'&sup2;', ")
    f.write("'&sup3;', ")
    f.write("'&acute;', ")
    f.write("'&micro;', ")
    f.write("'&para;', ")
    f.write("'&middot;', ")
    f.write("'&cedil;', ")
    f.write("'&sup1;', ")
    f.write("'&ordm;', ")
    f.write("'&raquo;', ")
    f.write("'&frac14;', ")
    f.write("'&frac12;', ")
    f.write("'&frac34;', ")
    f.write("'&iquest;', ")
    f.write("'&Agrave;', ")
    f.write("'&Aacute;', ")
    f.write("'&Acirc;', ")
    f.write("'&Atilde;', ")
    f.write("'&Auml;', ")
    f.write("'&Aring;', ")
    f.write("'&AElig;', ")
    f.write("'&Ccedil;', ")
    f.write("'&Egrave;', ")
    f.write("'&Eacute;', ")
    f.write("'&Ecirc;', ")
    f.write("'&Euml;', ")
    f.write("'&Igrave;', ")
    f.write("'&Iacute;', ")
    f.write("'&Icirc;', ")
    f.write("'&Iuml;', ")
    f.write("'&ETH;', ")
    f.write("'&Ntilde;', ")
    f.write("'&Ograve;', ")
    f.write("'&Oacute;', ")
    f.write("'&Ocirc;', ")
    f.write("'&Otilde;', ")
    f.write("'&Ouml;', ")
    f.write("'&times;', ")
    f.write("'&Oslash;', ")
    f.write("'&Ugrave;', ")
    f.write("'&Uacute;', ")
    f.write("'&Ucirc;', ")
    f.write("'&Uuml;', ")
    f.write("'&Yacute;', ")
    f.write("'&THORN;', ")
    f.write("'&szlig;', ")
    f.write("'&agrave;', ")
    f.write("'&aacute;', ")
    f.write("'&acirc;', ")
    f.write("'&atilde;', ")
    f.write("'&auml;', ")
    f.write("'&aring;', ")
    f.write("'&aelig;', ")
    f.write("'&ccedil;', ")
    f.write("'&egrave;', ")
    f.write("'&eacute;', ")
    f.write("'&ecirc;', ")
    f.write("'&euml;', ")
    f.write("'&igrave;', ")
    f.write("'&iacute;', ")
    f.write("'&icirc;', ")
    f.write("'&iuml;', ")
    f.write("'&eth;', ")
    f.write("'&ntilde;', ")
    f.write("'&ograve;', ")
    f.write("'&oacute;', ")
    f.write("'&ocirc;', ")
    f.write("'&otilde;', ")
    f.write("'&ouml;', ")
    f.write("'&divide;', ")
    f.write("'&oslash;', ")
    f.write("'&ugrave;', ")
    f.write("'&uacute;', ")
    f.write("'&ucirc;', ")
    f.write("'&uuml;', ")
    f.write("'&yacute;', ")
    f.write("'&thorn;', ")
    f.write("'&yuml;', ")
    f.write("'&euro;'];")
    f.close()
end